### ISSUE TITLE
Run DPO_pLM.sh something wrong

### ISSUE THREAD

**Issue by ysy-scu** [AI4PDLab/DPO_pLM#1]
Dear author
very nice work for enzyme area, but when I run the DPO_pLM.sh, there is an error
Traceback (most recent call last):
  File "/root/autodl-tmp/shiyangyou/DPO_pLM/DPO_pLM.py", line 340, in <module>
    dataset = generate_dataset(args.iteration_num, args.ec_label.strip(), args.mode)
  File "/root/autodl-tmp/shiyangyou/DPO_pLM/DPO_pLM.py", line 99, in generate_dataset
    data["weight"].append(len(lenght_rew))
TypeError: object of type 'float' has no len()
How to solve this problem？
Best wishes
Y

**Comment by StoccoFilippo** [comment]
Hello! Thanks for reaching out! I am about to update the code in the few hours and I will be back to you!
Best, Filippo

**Comment by StoccoFilippo** [comment]
Hi! corrected (there was an extra len()) and updated the scoring function in the template/example. Now should be fine :) try to pull the updates and let me know if any problem persist!

For now closing the issue
best,
F
